---

ansible_user: testuser

ansible_password: 

ansible_connection: winrm

ansible_winrm_server_cert_validation: ignore

ansible_winrm_transport: basic

ansible_winrm_port: 5985

ansible_python_interpreter: C:\Users\Administrator\AppData\Local\Programs\Python\Python39\
